# Generated by Django 2.0.2 on 2018-03-01 09:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bug',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=100)),
                ('issue', models.TextField(max_length=5000)),
                ('time', models.DateField(auto_now=True)),
                ('state', models.IntegerField(choices=[(0, '待解决'), (1, '已解决')], default=0)),
                ('like', models.IntegerField(choices=[(0, '未关注'), (1, '已关注')], default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publisher', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='bug',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Vange.Category'),
        ),
        migrations.AddField(
            model_name='bug',
            name='publisher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Vange.Publisher'),
        ),
    ]
