# Generated by Django 2.0.2 on 2018-02-26 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vange', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bug',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='bug',
            name='state',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='bug',
            name='time',
            field=models.DateField(auto_now=True),
        ),
    ]
