# Generated by Django 2.0.2 on 2018-03-02 06:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Vange', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bug',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Vange.Category', verbose_name='项目名称'),
        ),
        migrations.AlterField(
            model_name='bug',
            name='issue',
            field=models.TextField(max_length=5000, verbose_name='问题描述'),
        ),
        migrations.AlterField(
            model_name='bug',
            name='like',
            field=models.IntegerField(choices=[(0, '未关注'), (1, '已关注')], default=0, verbose_name='特别关注'),
        ),
        migrations.AlterField(
            model_name='bug',
            name='publisher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Vange.Publisher', verbose_name='发布者'),
        ),
        migrations.AlterField(
            model_name='bug',
            name='state',
            field=models.IntegerField(choices=[(0, '待解决'), (1, '已解决')], default=0, verbose_name='是否解决'),
        ),
        migrations.AlterField(
            model_name='bug',
            name='time',
            field=models.DateField(auto_now=True, verbose_name='发布时间'),
        ),
        migrations.AlterField(
            model_name='bug',
            name='title',
            field=models.CharField(default='', max_length=100, verbose_name='概要说明'),
        ),
    ]
