# Generated by Django 2.0.2 on 2018-03-02 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vange', '0002_auto_20180302_1440'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bug',
            options={'verbose_name': 'Bug列表', 'verbose_name_plural': 'Bug列表'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': '项目列表', 'verbose_name_plural': '项目列表'},
        ),
        migrations.AlterModelOptions(
            name='publisher',
            options={'verbose_name': '测试人员', 'verbose_name_plural': '测试人员'},
        ),
        migrations.AlterField(
            model_name='bug',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
