# Generated by Django 2.0.2 on 2018-02-26 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vange', '0002_auto_20180226_1626'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='addtime',
            field=models.DateField(auto_now=True),
        ),
    ]
