# Generated by Django 2.0.2 on 2018-03-02 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vange', '0003_auto_20180302_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bug',
            name='id',
            field=models.IntegerField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
