# Generated by Django 2.0.1 on 2018-01-21 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='master',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=50)),
                ('come', models.CharField(max_length=50)),
                ('content', models.CharField(max_length=5000)),
                ('timestr', models.CharField(max_length=50)),
                ('fid', models.CharField(max_length=50)),
                ('mid', models.CharField(max_length=5000)),
                ('datelong', models.CharField(max_length=50)),
                ('hrefStr', models.CharField(max_length=50)),
                ('href', models.CharField(max_length=200)),
                ('imgs', models.CharField(max_length=2000)),
            ],
        ),
    ]
