# Generated by Django 2.0.2 on 2018-03-06 08:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('masterWeiBo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like_date', models.DateField(auto_now=True)),
                ('like_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masterWeiBo.master', unique=True)),
            ],
        ),
    ]
