# Generated by Django 2.0.2 on 2018-03-06 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterWeiBo', '0002_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='like_user',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='master',
            name='mid',
            field=models.CharField(max_length=50),
        ),
    ]
