# Generated by Django 2.0.2 on 2018-03-07 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterWeiBo', '0003_auto_20180306_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='like_id',
            field=models.IntegerField(),
        ),
    ]
