# Generated by Django 2.0.2 on 2018-03-08 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterWeiBo', '0005_wordcloud'),
    ]

    operations = [
        migrations.CreateModel(
            name='WordPattern',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('img', models.ImageField(upload_to='')),
            ],
        ),
        migrations.AddField(
            model_name='wordcloud',
            name='pattern',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
