# Generated by Django 2.0.2 on 2018-03-27 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterWeiBo', '0006_auto_20180308_1540'),
    ]

    operations = [
        migrations.CreateModel(
            name='Statistics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=200)),
                ('date', models.DateField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='wordpattern',
            name='img',
            field=models.ImageField(upload_to='public/media'),
        ),
    ]
