# Generated by Django 2.0.2 on 2018-03-27 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterWeiBo', '0007_auto_20180327_1018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statistics',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
