# Generated by Django 2.0.2 on 2018-03-27 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterWeiBo', '0009_science'),
    ]

    operations = [
        migrations.AddField(
            model_name='science',
            name='mainActivity',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
