# Generated by Django 2.0.2 on 2018-03-27 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterWeiBo', '0010_science_mainactivity'),
    ]

    operations = [
        migrations.AddField(
            model_name='science',
            name='icon',
            field=models.ImageField(default=1, upload_to='public/media'),
            preserve_default=False,
        ),
    ]
