# Generated by Django 2.0.2 on 2018-03-27 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('masterWeiBo', '0011_science_icon'),
    ]

    operations = [
        migrations.RenameField(
            model_name='science',
            old_name='package',
            new_name='packageName',
        ),
    ]
