# Generated by Django 2.0.2 on 2018-03-27 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterWeiBo', '0012_auto_20180327_1413'),
    ]

    operations = [
        migrations.AddField(
            model_name='science',
            name='file',
            field=models.FileField(default=1, upload_to='public/'),
            preserve_default=False,
        ),
    ]
