# Generated by Django 2.0.2 on 2018-03-27 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('masterWeiBo', '0013_science_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='science',
            name='url',
        ),
    ]
