# Generated by Django 2.0.2 on 2018-03-27 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('masterWeiBo', '0014_remove_science_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='science',
            old_name='file',
            new_name='url',
        ),
    ]
