# Generated by Django 2.0.2 on 2018-03-28 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterWeiBo', '0015_auto_20180327_1800'),
    ]

    operations = [
        migrations.AddField(
            model_name='statistics',
            name='ip',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
