# Generated by Django 2.0.2 on 2018-03-28 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterWeiBo', '0016_statistics_ip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='science',
            name='url',
            field=models.FileField(null=True, upload_to='public/'),
        ),
    ]
