# Generated by Django 2.0.2 on 2018-03-28 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterWeiBo', '0017_auto_20180328_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='science',
            name='url',
            field=models.FileField(default='', upload_to='public/'),
        ),
    ]
