# Generated by Django 2.0.2 on 2018-03-28 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterWeiBo', '0019_auto_20180328_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='science',
            name='mainActivity',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='science',
            name='url',
            field=models.FileField(default=None, upload_to='public/'),
        ),
    ]
