# Generated by Django 2.0.2 on 2018-05-14 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterWeiBo', '0020_auto_20180328_1638'),
    ]

    operations = [
        migrations.CreateModel(
            name='Download',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=200)),
                ('ip', models.CharField(max_length=200)),
                ('date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Update',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appSize', models.CharField(max_length=200)),
                ('updateInformation', models.CharField(max_length=200)),
                ('updateNumber', models.IntegerField()),
                ('versionNumber', models.CharField(max_length=200, null=True)),
                ('downloadLink', models.CharField(max_length=200, null=True)),
                ('date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='science',
            name='mainActivity',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='science',
            name='packageName',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='science',
            name='url',
            field=models.FileField(null=True, upload_to='public/'),
        ),
    ]
