# Generated by Django 2.0.2 on 2018-05-18 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterWeiBo', '0021_auto_20180514_1133'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('category', models.CharField(max_length=100)),
                ('wordsTop10', models.CharField(max_length=1000)),
            ],
        ),
        migrations.AddField(
            model_name='wordcloud',
            name='img',
            field=models.ImageField(default='cc', upload_to='public/media'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wordcloud',
            name='name',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='wordpattern',
            name='img',
            field=models.ImageField(default=None, upload_to='public/media'),
        ),
    ]
